In [3]:
import anomaly_detection
from datetime import datetime
from IPython.display import display, HTML
from numpy import nan
import numpy as np

desiredComponents = ['Thermafuser']

startDateTime = datetime(2017, 1, 1, hour=0, minute=0, second=0, microsecond=0)
endDateTime = datetime(2017, 1, 1, hour=0, minute=10, second=0, microsecond=0)
    
dataFrames = anomaly_detection.loadData(startDateTime, endDateTime, desiredComponents)
arrays = anomaly_detection.getDataForGaussianAnalysis(dataFrames)

for key in arrays:
    print(key, arrays[key].shape)
    print(arrays[key])

Connection to mysql+mysqldb://localhost:3306/HVAC successfull
2017-01-01 00:00:00 2017-01-01 00:10:00 [<class 'hvacDBMapping.ThermafuserReading'>]
ThermafuserReadings (234, 5)
[[  46.    76.    70.    77.5   67.7]
 [  21.    76.    70.    90.    71.1]
 [  21.    76.    70.    71.8   64.4]
 ..., 
 [   0.    90.    60.    74.4   72.8]
 [ 129.    90.    60.    61.2   59.4]
 [  57.    90.    60.    62.5   63.6]]
